/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AppRouteImport } from './routes/_app'
import { Route as AppIndexRouteImport } from './routes/_app/index'
import { Route as AppTalentMatrixRouteImport } from './routes/_app/talent-matrix'
import { Route as AppNewJoinersRouteImport } from './routes/_app/new-joiners'
import { Route as AppAttritionRouteImport } from './routes/_app/attrition'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const AppTalentMatrixRoute = AppTalentMatrixRouteImport.update({
  id: '/talent-matrix',
  path: '/talent-matrix',
  getParentRoute: () => AppRoute,
} as any)
const AppNewJoinersRoute = AppNewJoinersRouteImport.update({
  id: '/new-joiners',
  path: '/new-joiners',
  getParentRoute: () => AppRoute,
} as any)
const AppAttritionRoute = AppAttritionRouteImport.update({
  id: '/attrition',
  path: '/attrition',
  getParentRoute: () => AppRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof AppIndexRoute
  '/login': typeof LoginRoute
  '/attrition': typeof AppAttritionRoute
  '/new-joiners': typeof AppNewJoinersRoute
  '/talent-matrix': typeof AppTalentMatrixRoute
}
export interface FileRoutesByTo {
  '/login': typeof LoginRoute
  '/attrition': typeof AppAttritionRoute
  '/new-joiners': typeof AppNewJoinersRoute
  '/talent-matrix': typeof AppTalentMatrixRoute
  '/': typeof AppIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_app': typeof AppRouteWithChildren
  '/login': typeof LoginRoute
  '/_app/attrition': typeof AppAttritionRoute
  '/_app/new-joiners': typeof AppNewJoinersRoute
  '/_app/talent-matrix': typeof AppTalentMatrixRoute
  '/_app/': typeof AppIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/login' | '/attrition' | '/new-joiners' | '/talent-matrix'
  fileRoutesByTo: FileRoutesByTo
  to: '/login' | '/attrition' | '/new-joiners' | '/talent-matrix' | '/'
  id:
    | '__root__'
    | '/_app'
    | '/login'
    | '/_app/attrition'
    | '/_app/new-joiners'
    | '/_app/talent-matrix'
    | '/_app/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AppRoute: typeof AppRouteWithChildren
  LoginRoute: typeof LoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/': {
      id: '/_app/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/talent-matrix': {
      id: '/_app/talent-matrix'
      path: '/talent-matrix'
      fullPath: '/talent-matrix'
      preLoaderRoute: typeof AppTalentMatrixRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/new-joiners': {
      id: '/_app/new-joiners'
      path: '/new-joiners'
      fullPath: '/new-joiners'
      preLoaderRoute: typeof AppNewJoinersRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/attrition': {
      id: '/_app/attrition'
      path: '/attrition'
      fullPath: '/attrition'
      preLoaderRoute: typeof AppAttritionRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppRouteChildren {
  AppAttritionRoute: typeof AppAttritionRoute
  AppNewJoinersRoute: typeof AppNewJoinersRoute
  AppTalentMatrixRoute: typeof AppTalentMatrixRoute
  AppIndexRoute: typeof AppIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppAttritionRoute: AppAttritionRoute,
  AppNewJoinersRoute: AppNewJoinersRoute,
  AppTalentMatrixRoute: AppTalentMatrixRoute,
  AppIndexRoute: AppIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AppRoute: AppRouteWithChildren,
  LoginRoute: LoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
