/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AppRouteImport } from './routes/_app'
import { Route as AppIndexRouteImport } from './routes/_app/index'
import { Route as AppTalentMatrixRouteImport } from './routes/_app/talent-matrix'
import { Route as AppRiskMethodologyRouteImport } from './routes/_app/risk-methodology'
import { Route as AppAttritionRouteImport } from './routes/_app/attrition'
import { Route as AppAdminRouteImport } from './routes/_app/admin'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const AppTalentMatrixRoute = AppTalentMatrixRouteImport.update({
  id: '/talent-matrix',
  path: '/talent-matrix',
  getParentRoute: () => AppRoute,
} as any)
const AppRiskMethodologyRoute = AppRiskMethodologyRouteImport.update({
  id: '/risk-methodology',
  path: '/risk-methodology',
  getParentRoute: () => AppRoute,
} as any)
const AppAttritionRoute = AppAttritionRouteImport.update({
  id: '/attrition',
  path: '/attrition',
  getParentRoute: () => AppRoute,
} as any)
const AppAdminRoute = AppAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AppRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof AppIndexRoute
  '/login': typeof LoginRoute
  '/admin': typeof AppAdminRoute
  '/attrition': typeof AppAttritionRoute
  '/risk-methodology': typeof AppRiskMethodologyRoute
  '/talent-matrix': typeof AppTalentMatrixRoute
}
export interface FileRoutesByTo {
  '/login': typeof LoginRoute
  '/admin': typeof AppAdminRoute
  '/attrition': typeof AppAttritionRoute
  '/risk-methodology': typeof AppRiskMethodologyRoute
  '/talent-matrix': typeof AppTalentMatrixRoute
  '/': typeof AppIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_app': typeof AppRouteWithChildren
  '/login': typeof LoginRoute
  '/_app/admin': typeof AppAdminRoute
  '/_app/attrition': typeof AppAttritionRoute
  '/_app/risk-methodology': typeof AppRiskMethodologyRoute
  '/_app/talent-matrix': typeof AppTalentMatrixRoute
  '/_app/': typeof AppIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/admin'
    | '/attrition'
    | '/risk-methodology'
    | '/talent-matrix'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/login'
    | '/admin'
    | '/attrition'
    | '/risk-methodology'
    | '/talent-matrix'
    | '/'
  id:
    | '__root__'
    | '/_app'
    | '/login'
    | '/_app/admin'
    | '/_app/attrition'
    | '/_app/risk-methodology'
    | '/_app/talent-matrix'
    | '/_app/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AppRoute: typeof AppRouteWithChildren
  LoginRoute: typeof LoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/': {
      id: '/_app/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/talent-matrix': {
      id: '/_app/talent-matrix'
      path: '/talent-matrix'
      fullPath: '/talent-matrix'
      preLoaderRoute: typeof AppTalentMatrixRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/risk-methodology': {
      id: '/_app/risk-methodology'
      path: '/risk-methodology'
      fullPath: '/risk-methodology'
      preLoaderRoute: typeof AppRiskMethodologyRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/attrition': {
      id: '/_app/attrition'
      path: '/attrition'
      fullPath: '/attrition'
      preLoaderRoute: typeof AppAttritionRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/admin': {
      id: '/_app/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AppAdminRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppRouteChildren {
  AppAdminRoute: typeof AppAdminRoute
  AppAttritionRoute: typeof AppAttritionRoute
  AppRiskMethodologyRoute: typeof AppRiskMethodologyRoute
  AppTalentMatrixRoute: typeof AppTalentMatrixRoute
  AppIndexRoute: typeof AppIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppAdminRoute: AppAdminRoute,
  AppAttritionRoute: AppAttritionRoute,
  AppRiskMethodologyRoute: AppRiskMethodologyRoute,
  AppTalentMatrixRoute: AppTalentMatrixRoute,
  AppIndexRoute: AppIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AppRoute: AppRouteWithChildren,
  LoginRoute: LoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
